language: python
python:
  - { PATH: "{{replace(Python36, '\\', '\\\\')}}", VERSION: 3.6, DIST: std }
virtualenv:
  - path: {{ospathjoin(root_path, pickname("%NAME_JENKINS%", project_name + "_%VERSION%_%DIST%_%NAME%"), "_venv")}}
before_script:
    # regular expression for Jekins view: ((.*PUBLISH.*)|(.*PYPI.*))|(.*36.*.*((std)|(STD)).*)
  -  if [ "PYPI" not in ${NAME} ] then pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyquickhelper pyensae pymmails pymyinstall pyrsslocal ensae_teaching_cs fi
  -  if [ "PYPI" in ${NAME} ] then pip install pyquickhelper fi
script:
  - { CMD: "python jenkins\\publish_lectures.py", NAME: "PUBLISH", TIMEOUT: 3600, SCHEDULER: "FIXED H 4 * * *" }
  - { CMD: "python jenkins\\start_pypi.py", NAME: "PYPI", SCHEDULER: "STARTUP" }
